server:
  address: "corecast.bitquery.io"
  authorization: "ory_at_RZn6icn8P2_RxKnB2OFZBnndN21JWXrGr2QDb98MevE.CGFYvLoyvDefJi1iO_P0AMhqea1GY8cHQrxAqElm9gk"
  insecure: false

stream:
  type: "transactions"

filters:
  programs: # Transaction.ParsedIdlInstructions[0].Program
    - "pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA" # pumpswap
    - "SoLFiHG9TfgtdUXUjWAxi3LtvYuFyDLVhBWxdMZxyCe" # solfi
    - "PhoeNiXZ8ByJGLkxNfZRnkUfjvmuYqLR89jjFHGqdXY" # phoenix
    - "BSwp6bEBihVLdqJRKGgzjcGLHkcTuzmSo1TQkHepzH8p" # bonkswap
    - "obriQD1zbpyLz95G5n7nJe6a4DPjpFwa5XYPoNm113y" # obric
    - "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4" # jupiter
