server:
  address: "corecast.bitquery.io"
  authorization: "ory_"
  insecure: false

stream:
  type: "transactions"
  
filters:
  programs: # Transaction.ParsedIdlInstructions[0].Program
    - "opnb2LAfJYbRMAHHvqjCwQxanZn7ReEHp1k81EohpZb"  # openbook