server:
  address: "corecast.bitquery.io"
  authorization: "ory_at_"
  insecure: false

stream:
  type: "balances"

filters:
  addresses:
    - "DSqMPMsMAbEJVNuPKv1ZFdzt6YvJaDPDddfeW7ajtqds"
  tokens:
    - "So11111111111111111111111111111111111111112" # SOL
