server:
  address: "corecast.bitquery.io"
  authorization: "${AUTHORIZATION_TOKEN}"
  insecure: false

stream:
  type: "transactions"
  
filters:
  signers:
    - "ETcW7iuVraMKLMJayNCCsr9bLvKrJPDczy1CMVMPmXTc"