server:
  address: "corecast.bitquery.io"
  authorization: "ory_at_RZn6icn8P2_RxKnB2OFZBnndN21JWXrGr2QDb98MevE.CGFYvLoyvDefJi1iO_P0AMhqea1GY8cHQrxAqElm9gk"
  insecure: false

stream:
  type: "transfers"

filters:
  senders:
    - "DSqMPMsMAbEJVNuPKv1ZFdzt6YvJaDPDddfeW7ajtqds"
  receivers:
    - "ReceiverAddressHere..."
  tokens:
    - "So11111111111111111111111111111111111111112" # SOL
    - "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v" # USDC
